In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
# Библлиотека для работы с многомерными массивами

arr = np.arange(24)
bar = list(range(100000))

In [ ]:
%time for i in range(10): a2 = arr * 2
%time for i in range(10): b2 = [i*2 for i in bar]

CPU times: user 2.84 ms, sys: 0 ns, total: 2.84 ms
Wall time: 8.38 ms
CPU times: user 71.5 ms, sys: 17.9 ms, total: 89.4 ms
Wall time: 89.5 ms


In [ ]:
arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
b = arr.reshape(4, 6)

In [ ]:
arr.reshape(2, 2, 2, 3)[0]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
arr.reshape(2, 2, 2, 3)[0][0]

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(2, 2, 2, 3)[0, 0, 0, 0]

0

In [ ]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b.shape

(4, 6)

In [ ]:
b.ndim

2

In [ ]:
b.size

24

In [ ]:
b.itemsize

8

In [ ]:
a = np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
np.array([1.1, 1.2, 1.3, 1.4]).dtype

dtype('float64')

In [ ]:
np.random.random(size=10)

array([0.58800425, 0.33774583, 0.31737985, 0.21902714, 0.9681703 ,
       0.19164587, 0.44470286, 0.32261518, 0.09228377, 0.80954409])

In [ ]:
np.random.randint(low = 1, high = 10000, size=(5, 5))

array([[3072, 6200, 1611, 2035, 8721],
       [8833, 9770, 5487, 7355, 3906],
       [3033, 4481, 1659, 2078, 1219],
       [8004, 9729, 6568, 8854, 3868],
       [ 705, 4109, 2265, 2456, 5026]])

In [ ]:
np.linspace(0, 1, 101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [ ]:
a = np.linspace(0, 1, 5)
b = np.arange(5)

In [ ]:
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
b

array([0, 1, 2, 3, 4])

In [ ]:
a*b

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [ ]:
a+b

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
a**b

array([1.      , 0.25    , 0.25    , 0.421875, 1.      ])

In [ ]:
a@b

7.5

In [ ]:
a > b

array([False, False, False, False, False])

In [ ]:
a <= 0.5

array([ True,  True,  True, False, False])

In [ ]:
a[a <= 0.5]

array([0.  , 0.25, 0.5 ])

In [ ]:
# if             True False
np.where(a <= 0.5, a, 1)

array([0.  , 0.25, 0.5 , 1.  , 1.  ])

In [ ]:
a = np.zeros((10, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.ones((10, 10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.random.random(size=(10, 10))

array([[0.61980391, 0.54101738, 0.93711986, 0.62591651, 0.37486075,
        0.0342303 , 0.15041689, 0.47326162, 0.72007001, 0.56794187],
       [0.25762169, 0.72443391, 0.21474515, 0.10174854, 0.63115404,
        0.52327604, 0.03580496, 0.7318937 , 0.4099848 , 0.76386671],
       [0.48778274, 0.6955878 , 0.94710222, 0.90969021, 0.96284244,
        0.54960151, 0.38414437, 0.30548655, 0.4155359 , 0.07920561],
       [0.03678882, 0.57577406, 0.14822349, 0.62931658, 0.58306713,
        0.4510782 , 0.81490468, 0.97102636, 0.24015985, 0.60931161],
       [0.64369014, 0.14053269, 0.01892958, 0.39788358, 0.56244596,
        0.38803164, 0.84146594, 0.62289551, 0.66681426, 0.94306954],
       [0.90307308, 0.71738649, 0.62230811, 0.86780051, 0.23824541,
        0.50093643, 0.0508111 , 0.18563701, 0.99093341, 0.60478154],
       [0.85830695, 0.50090912, 0.57809906, 0.4882686 , 0.32786903,
        0.86874379, 0.17278931, 0.37114577, 0.78410197, 0.26595715],
       [0.34208931, 0.16519294, 0.4368177

In [ ]:
np.random.random(size=(10, 10)).T

array([[0.63671464, 0.35596959, 0.52646494, 0.7176044 , 0.74218655,
        0.10491211, 0.44152186, 0.52345157, 0.30818765, 0.66246512],
       [0.11715582, 0.40403778, 0.8090376 , 0.84540523, 0.03835414,
        0.21832403, 0.08984592, 0.16714887, 0.42743683, 0.30970434],
       [0.92478673, 0.38807502, 0.20350362, 0.23774147, 0.39855841,
        0.631837  , 0.75794524, 0.47518548, 0.28923547, 0.97079034],
       [0.44159066, 0.00267078, 0.68158924, 0.57707713, 0.00966865,
        0.21483646, 0.3130556 , 0.34172054, 0.69350976, 0.40755125],
       [0.68631014, 0.1992043 , 0.59610174, 0.89269078, 0.41328921,
        0.14974861, 0.61736923, 0.78540088, 0.5711514 , 0.67407498],
       [0.70059208, 0.08818104, 0.08419836, 0.73821805, 0.72148442,
        0.43639488, 0.15427032, 0.40329974, 0.60405428, 0.42321308],
       [0.44262583, 0.11896288, 0.20822487, 0.41508139, 0.5497967 ,
        0.0741966 , 0.14770645, 0.56911523, 0.80468538, 0.82469196],
       [0.47045643, 0.64784692, 0.2339067

In [ ]:
a = np.arange(9).reshape(3, 3)
b = np.arange(3).reshape(1, 3)
print(a, end='\n\n')
print(b, end='\n\n')
a*b

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]]



array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [ ]:
a*a

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
a.dot(b.T)

array([[ 5],
       [14],
       [23]])

In [ ]:
a[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [ ]:
np.vstack([a, b])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [ ]:
mat = np.matrix(a)

In [ ]:
mat

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
mat.sum()

36

In [ ]:
mat = np.eye(10)
mat

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.where(mat != 0)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
np.nonzero(mat)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
mar = np.matrix(np.random.randint(0, 10, 100).reshape(10, 10))
mar

matrix([[5, 3, 5, 9, 7, 4, 6, 4, 7, 8],
        [7, 8, 8, 2, 5, 8, 4, 1, 2, 5],
        [0, 5, 3, 6, 1, 2, 4, 3, 2, 0],
        [4, 2, 2, 7, 4, 8, 0, 5, 3, 4],
        [1, 4, 6, 1, 6, 5, 7, 5, 9, 3],
        [4, 9, 1, 6, 2, 4, 6, 3, 7, 3],
        [5, 7, 5, 6, 9, 8, 6, 8, 2, 3],
        [4, 3, 4, 8, 8, 3, 4, 4, 6, 1],
        [4, 2, 9, 5, 6, 7, 6, 5, 7, 8],
        [9, 8, 0, 1, 9, 2, 0, 3, 6, 2]])

In [ ]:
mar.max()

9

In [ ]:
mar.min()

0

In [ ]:
mar.mean()

5.07

In [ ]:
mar[0, :] = 1
mar[:, 0] = 1
mar[:, 9] = 1
mar[9, :] = 1
mar

matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 8, 8, 2, 5, 8, 4, 1, 2, 1],
        [1, 5, 3, 6, 1, 2, 4, 3, 2, 1],
        [1, 2, 2, 7, 4, 8, 0, 5, 3, 1],
        [1, 4, 6, 1, 6, 5, 7, 5, 9, 1],
        [1, 9, 1, 6, 2, 4, 6, 3, 7, 1],
        [1, 7, 5, 6, 9, 8, 6, 8, 2, 1],
        [1, 3, 4, 8, 8, 3, 4, 4, 6, 1],
        [1, 2, 9, 5, 6, 7, 6, 5, 7, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
mar[1:-1, 1:-1] = 0
mar

matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
a = np.eye(10)
np.diag(a, k = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Below main diagonal 
np.diag(a, k = -1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Above main diagonal 
np.diag(a, k = 1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a = np.diag(np.arange(1, 5), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
a = np.diag(np.arange(1, 5), k = 0)
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
a = np.matrix(np.arange(15).reshape(5, 3))
b = np.matrix(np.arange(6).reshape(3, 2))
a

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
b

matrix([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
a*b

matrix([[ 10,  13],
        [ 28,  40],
        [ 46,  67],
        [ 64,  94],
        [ 82, 121]])

In [ ]:
a@b

matrix([[ 10,  13],
        [ 28,  40],
        [ 46,  67],
        [ 64,  94],
        [ 82, 121]])

In [ ]:
abc = np.arange(25)
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.where((abc < 5) | (abc > 15), -abc, abc)

array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15, -16, -17, -18, -19, -20, -21, -22, -23, -24])